### ISSUE TITLE
Which option is going to cost money?

### ISSUE THREAD

**Issue by shivamhw** [meashishsaini/bsnl#1]
I got 4GB topup in my bsnl fup details page after just sending a blank GET request to the 4GB and 10GB link specified in your data.py . What is that supposed to mean?
am i going to get charged extra?

**Comment by meashishsaini** [comment]
These are promotional packs BSNL give randomly to customers. I apply 4GB promotional everyday for that extra data. I never got charged for it. You can try doing it just once for the month and looking at the bill if you got charged.

**Comment by shivamhw** [comment]
Ohh thanks.. i have few questions, please try to answer that would be a big
help.

1. Can you apply 4gb limitess times a day or its fixed for 1 time a day.
2. What is difference in 10gb monthly one and 4 gb daily one
3. Please give a sample command to start your program. I m having some
trouble and i guess i m not passing proper arguments


I loved your script its too professional and coding style is clear. Even if
you don't reply than also thanks for uploading it on GITHUB

**Comment by meashishsaini** [comment]
1. No, just once per day.
2. In 10 GB monthly, you will get 10 GB for a month. In 4 GB daily, you will get 4 GB for a day.
3. To activate daily 4 GB use `bsnl --activate Daily_4GB_Promotional`.
Thanks
